### ISSUE TITLE
Suggested Correction - Page 56 - Cross Platform Setup

### ISSUE THREAD

**Issue by carcharo** [PacktPublishing/ASP.NET-Core-5-for-Beginners#13]
Hi,

Tried to submit an errata on the Packt site but kept getting an error that requested URL was rejected.

Think found a missing step and command correction in the setup of WSL2 on Page 56. After creating the LinuxHelloWorld folder and going in, the VI will fail to find the index.cshtml file. The Mac version is correct hence copied the command from there.

This is due to the .Net project not being created and the path in VI is missing an 's' in Views. Please see below the suggested update. Added in the missing step so new step 2 and corrected the path when calling VI.

1. Create a new directory and change into it:
```mkdir LinuxHelloWorld && cd LinuxHelloWorld```

2. Create ASP.NET Core Web App (Model-View-Controller) using:
```dotnet new mvc```

2. Linux running in WSL2 does not support a graphical UI yet, so we need to do the editing via non-graphical utilities:
```sudo vi Views/Home/Index.cshtml```

After that the steps are okay and expected result is shown in web page. Hope helps any others if come across this.

**Comment by sarvesh-packt** [comment]
Hi @carcharo,

We have confirmed this with the Author and the solution is correct. 

Regards,
