### ISSUE TITLE
DEV settings not developy-enough

### ISSUE THREAD

**Issue by DickBaker** [PacktPublishing/ASP.NET-Core-5-for-Beginners#15]
The appsettings.Development.json is almost the same as the appsettings.json sibling, whereas
1. DEV is missing the "AllowedHosts": "*" (if anything you might expect Prod version to be more restrictive)
2. imho DEV flavour could be "Default": "Verbose" just to show some useful variation

**Comment by proudmonkey** [comment]
Thank you for the feedback.

You don't have to explicity define `AllowedHosts` in DEV appSettings as the the framework will just pick up whatever settings you have from the default `appSettings.json`. If you want to override some settings from the default `appSettings.json` then you are free to do so in a different  appSettings files like DEV, TEST, STAGE or PROD.

**Comment by DickBaker** [comment]
sure, but if DEV and PROD are the same you don't need secondary env-specific config.
My point wasn't [really] adding the optional AllowedHosts clause to make them more similar [but if you _like_ AllowedHosts you probably would], but to make them more different to satisfy the distinct foibles of each env

**Comment by proudmonkey** [comment]
> but if DEV and PROD are the same you don't need secondary env-specific config.

Having a separate env-specific config won't hurt you. In fact, the Dev config is part of the default file generated when you create a new project from Visual Studio template. I think the goal is to guide/let the devs know that you can setup whatever env-specific config there instead of just adding them all in `appSettings.json`. In reality, apps should have at least two configs, (DEV and PROD), and both should have different settings.

**Comment by DickBaker** [comment]
Understood that _AllowedHosts_ is optional, and presumably MS include that clause in the PROD file as a reminder that maybe they **should** whitelist intended sites [whereas DEVs are unlikely to care about security niceties]. I agree that the different env files **should** be different [especially for logging], but the only difference was that _AllowedHosts_ clause [that doesn't matter much in dev-land] which is why I raised the issue. 

The MS templates (e.g. Empty) generates those 2 files [exactly as your code download], so really my complaint is with the MS templates and not anything that you authors have invented [my bad assumption!]

The PDF for the book (p259/603) describes pecking order well enough, but most templates will create the appsettings files automatically so users won't have to manually create as instructed on pp507-509 [that also well describe Logging knobs].

I think we agree so I'm closing this Issue #15 now. Thanks for your time Vince.
