### ISSUE TITLE
SLN file is old-school not modern SDK, and de-dinosaur the text

### ISSUE THREAD

**Issue by DickBaker** [PacktPublishing/ASP.NET-Core-5-for-Beginners#16]
Can you PLEASE also change the outdated instruction to "unload Project.. reload the project". Assuming readers have the VS2019 code there is no justification for this throw-back [i.e. log an Erratum to educ8 users proper!]

**Comment by adwaitu** [comment]
Thanks for your suggestion. We will pass it onto the authors for incorporating it into an Erratum for the current edition and as an enhancement for the next edition.

**Comment by sarvesh-packt** [comment]
Hi, 

Please reopen if the issue still persists.

Regards,
